---
title: "analysis"
author: "Chunhui Gu"
date: "2024-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(protools)
```


# Load data
```{r}
(df <- read.csv('data/results.csv', row.names =1))
colnames(df) <- gsub('sample_', '', colnames(df))

```


## Heatmap without normalization
```{r}
pheatmap::pheatmap(log10(as.matrix(df) + 1), cluster_rows = FALSE, cluster_cols = FALSE, show_rownames = FALSE, show_colnames = TRUE,
                   angle_col = 315, fontsize_col = 8)
```


## Heatmap with total count normalization
https://support.proteomesoftware.com/hc/en-us/articles/115002739586-Spectrum-Count-Normalization-in-Scaffold

No much difference between normalized and non-normalized. So I will use non-normalized data for further analysis.
```{r}
df_tc_norm <- protools::total_spectral_count_norm(df)
pheatmap::pheatmap(log10(as.matrix(df_tc_norm) + 1), cluster_rows = FALSE, cluster_cols = FALSE, show_rownames = FALSE, show_colnames = TRUE,
                   angle_col = 315, fontsize_col = 8)
```


## Calculate ratio of het vs wt
```{r}
df_het <- df[paste0('het_', 1:6)]
df_wt <- df[paste0('wt_', 1:6)]

# min_df <- min(df_ratio_het_wt[sapply(df_ratio_het_wt, is.finite)])

df_ratio_het_wt <- df_het / (df_wt + 10-6)

# max_finite <- max(df_ratio_het_wt[sapply(df_ratio_het_wt, is.finite)])
# 
# # Replace Inf with the maximum finite value
# df_ratio_het_wt[sapply(df_ratio_het_wt, is.infinite)] <- max_finite

colnames(df_ratio_het_wt) <- paste0('ratio_het_vs_wt_sample_', 1:6)

cbind(df, df_ratio_het_wt) %>% write.csv('data/results_with_ratio.csv')
```

<!-- # ratio for normalized data -->
<!-- ```{r} -->
<!-- df <- df_tc_norm -->
<!-- df_het <- df[paste0('sample_het_', 1:6)] -->
<!-- df_wt <- df[paste0('sample_wt_', 1:6)] -->

<!-- # min_df <- min(df_ratio_het_wt[sapply(df_ratio_het_wt, is.finite)]) -->

<!-- df_ratio_het_wt <- df_het / (df_wt + 10-6) -->

<!-- # max_finite <- max(df_ratio_het_wt[sapply(df_ratio_het_wt, is.finite)]) -->
<!-- #  -->
<!-- # # Replace Inf with the maximum finite value -->
<!-- # df_ratio_het_wt[sapply(df_ratio_het_wt, is.infinite)] <- max_finite -->

<!-- colnames(df_ratio_het_wt) <- paste0('ratio_het_vs_wt_sample_', 1:6) -->
<!-- ``` -->


## Heatmap for ratio of het vs wt (without normalization)
```{r}
pheatmap::pheatmap(log10(as.matrix(df_ratio_het_wt) + 1), cluster_rows = FALSE, cluster_cols = FALSE, show_rownames = FALSE, show_colnames = TRUE,
                   angle_col = 315, fontsize_col = 8)
```





## trend of ratio across 6 oxidize phenotypes (without normalization)
```{r}
sample_df <- log10(df_ratio_het_wt[sample(nrow(df_ratio_het_wt), 50), ] + 1)

rownames_to_column(sample_df, var = "gene") %>%
  pivot_longer(cols = -gene, names_to = "sample", values_to = "ratio") %>%
  # ggplot(aes(x = factor(sample, paste0("ratio_het_vs_wt_sample_", c(4, 5, 1, 2, 6, 3))), y = ratio, group=gene, color=gene)) +
  ggplot(aes(x = sample, y = ratio, group=gene, color=gene)) +
  geom_line() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  labs(title = "Trend of ratio across 6 oxidize phenotypes (50 genes randomly)", x = "paried sample", y = "log 10 count ratio") 
```



